apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: microservice2:latest
        ports:
        - containerPort: 5000

